services:
  bifrost:
    build: .
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - VALKEY_URL=redis://valkey:6379
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bifrost.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.bifrost.entrypoints=websecure
      - traefik.http.routers.bifrost.tls.certresolver=primary
      - traefik.http.services.bifrost.loadbalancer.server.port=8080
    networks:
      - bifrost
      - traefik

  postgres:
    image: postgres:18-alpine
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bifrost

  valkey:
    image: valkey/valkey:9-alpine
    networks:
      - bifrost

volumes:
  postgres:

networks:
  bifrost:
  traefik:
    external: true
